name: Build and test

on:
  push:
    branches:
      - main
      - answers
  pull_request:

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

jobs:

  cdct-with-pact-java:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run order-consumer tests
        working-directory: ./order-consumer
        run: mvn clean test

      - name: Publish order-consumer contract
        uses: pactflow/actions/publish-pact-files@v2
        with:
          pactfiles: ./order-consumer/target/pacts
          version: 1.0.0-order-${{ github.sha }}
          broker_url: ${{ env.PACT_BROKER_BASE_URL }}
          token: ${{ env.PACT_BROKER_TOKEN }}

      - name: Provider contract verification
        run: mvn clean "-Dpact.verifier.publishResults=true" "-Dpact.provider.version=1.0.0-address-${{ github.sha }}" test
